name: CI/CD for Vue.js Frontend

on:
  push:
    branches:
      - master # Adjust the branch as needed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can choose the Node.js version you need

    - name: Install Dependencies
      run: npm install

    - name: Build Vue.js App
      run: npm run build

    - name: Deploy to AWS Amplify
      uses: aws-amplify/github-action@v3
      with:
        amplifyAppId: ${{ secrets.AMPLIFY_APP_NAME }} # Replace with your Amplify App ID
        amplifyBranch: master # Adjust to your main branch
        awsAccessKeyId: ${{ secrets.AWS_ACCESS_KEY_ID }}
        awsSecretAccessKey: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
