name: CI/CD

on:
  push:
    branches:
      - frontend-punch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: npm install

    - name: Build Application
      run: npm run build

    - name: Archive Build
      uses: actions/upload-artifact@v2
      with:
        name: build
        path: dist

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Download Build
      uses: actions/download-artifact@v2
      with:
        name: build
        path: dist

    - name: Deploy to Server
      run: |
        npm install -g serve
        serve -s dist
