name: CI/CD

on:
  push:
    branches:
      - frontend-punch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    # Optionally, you can add test steps here
    # - name: Run tests
    #   run: npm run test

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Download production artifacts
      uses: actions/download-artifact@v2
      with:
        name: dist
        path: dist

    - name: Deploy to server
      # Add your deployment script or commands here, for example:
      run: |
        npm install -g serve
        serve dist
